export const ErrorMessage = {
  NONE: "NONE",
  UNKNOWN: "UNKNOWN",
  MISSING_PARAMETER: "Required parameter is missing.",
  INVALID_EMAIL_ADDRESS: "The email address provided is not valid.",
  EMAIL_ALREADY_EXIST: "This email address is already registered.",
  USERNAME_ALREADY_EXIST: "This username is already taken.",
  WRONG_USERNAME_OR_PASSWORD: "Incorrect username or password.",
  COULD_NOT_CHANGE_PASSWORD: "Failed to change password.",
  USER_NOT_FOUND: "User not found.",

  GAME_CONFIG_NOT_FOUND: "Game configuration not found.",
  TRANSACTION_NOT_FOUND: "Transaction not found.",
  TRANSACTION_ALREADY_ENDED: "This transaction has already been completed.",
  TRANSACTION_NOT_OWNER: "You are not the owner of this transaction.",
  INVALID_STORE_PRODUCT: "The store product is invalid.",
  INVALID_OFFLINE_PRODUCT: "The offline product is invalid.",
  PRODUCT_PURCHASE_LIMIT: "Purchase limit reached for this product.",
  PRODUCT_PURCHASE_LOCKED: "This product is currently locked.",
  PRODUCT_DISABLE: "This product is currently disabled.",
  INSUFFICIENT_RESOURCE: "You do not have enough resources.",

  INVALID_QUEST: "The quest is invalid.",
  QUEST_NOT_COMPLETE: "The quest has not been completed.",
  QUEST_ALREADY_CLAIMED: "This quest reward has already been claimed.",
  ALREADY_CHECK_IN: "You have already checked in today.",
  INVALID_GIFT: "The gift is invalid.",
  GIFT_ALREADY_CLAIMED: "This gift has already been claimed.",
  ACHIEVEMENT_NOT_COMPLETE: "The achievement has not been completed.",
  ACHIEVEMENT_ALREADY_CLAIMED: "This achievement reward has already been claimed.",

  INVALID_TUTORIAL: "The tutorial is invalid.",
  REQUIRE_TUTORIAL_NOT_FINISHED: "A required tutorial has not been completed.",
  TUTORIAL_NOT_STARTED: "The tutorial has not been started yet.",

  INVALID_COUPON: "Invalid coupon. You have [remainingAttempts] attempts remaining. If all are used up, try again tomorrow.",
  COUPON_EXPIRED_OR_NOT_STARTED: "Coupon usage period has expired or has not started yet.",
  COUPON_USAGE_LIMIT: "Coupon usage limit exceeded.",
  COUPON_FAILED_LIMIT: "You have made too many invalid coupon attempts. Please try again tomorrow.",
  COUPON_TYPE_ALREADY_USE: "You have already used a coupon of this type.",
  COUPON_CODE_ALREADY_USE: "You have already redeemed this coupon.",

  INVALID_QUESTION: "Invalid question Id",
  INVALID_LEADERBOARD: "Invalid leaderboard name",
  INVALID_USERNAME: "Invalid username. Only letters, numbers, underscores. No leading/trailing or double underscores. 3�100 characters.",
  
  INVALID_WALLET: "Invalid wallet",
  INVALID_GAME_ID: "Invalid gameId",
  INVALID_WINNER: "Winner did not participate",
  INVALID_MEZON_ID: "Invalid mezonId",
  INVALID_CURRENCY_TYPE: "Invalid currency type",
  VALIDATE_HASH_FAILED: "Verify hash value mismatch",

  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};